### ISSUE TITLE
Dashboard doesn't load if any of the trials have "Infinity" values

### ISSUE THREAD

**Issue by rajeshlal** [optuna/optuna-dashboard#108]
# Bug reports

In an Optuna study, if any of the trials returns Infinity (Inf) values, the dashboard does not load, a message saying "Failed to fetch study <study_id>" is shown on the lower left corner of the dashboard

## Expected Behavior

Ignore the Infinity values and show the dashboard for other values.

## Current Behavior and Steps to Reproduce

Open a study which has Inf values in at least one trial.

![image](https://user-images.githubusercontent.com/25330769/122087421-ae896c00-cdd2-11eb-87b0-b49f0d585d9a.png)

![image](https://user-images.githubusercontent.com/25330769/122087819-29528700-cdd3-11eb-9c75-af709f36066e.png)

I tried accessing the API at /api/studies/<study_id>, which shows some Inf values, e.g. ... "values": [Infinity] ...

Other studies which do not have Inf values, load and work as expected.

## Context
Please provide any relevant information about your setup.
This is important in case the issue is not reproducible except for under certain conditions.

  * `python -c 'import optuna; print(optuna.__version__)'`: 2.8.0
  * `optuna-dashboard --version`: 0.4.2

**Comment by niklasmohrin** [comment]
I stumbled upon this issue after I encountered the bug myself and I dug into this for a bit, here is what I found:

Serialization is broken somewhere. As you can see in the original report, Python's `math.inf` is serialized into the literal `Infinity` (which is valid javascript, but not JSON), but really should be the string `"Infinity"`. I also found this to be the case when testing. I also see the same happen with `NaN`, which is also valid in javascript, but not in json. I also found this snippet: `"user_attrs": [{"key": "metrics", "value": "[NaN, NaN, NaN]"}, /* snip */` which I found really funny first, but then I realized this is just a json serialized json string, because it is a user-attr.

According to [this thread I found](https://github.com/pandas-dev/pandas/issues/12213#issuecomment-178882085), some encoders do ~~the right~~something, such as encoding these special values as strings (which would work for this usecase). But of course, this isn't standardized anywhere, for example in Bottle, [the `ujson` library is used when it is available](https://github.com/bottlepy/bottle/blob/5a6c620b2a51adad2591e0d161d392cb8c0d4c50/bottle.py#L82). This makes everything more interesting:
```
>>> json.dumps(math.inf)
'Infinity'
>>> ujson.dumps(math.inf)
'Inf'
>>> json.loads(json.dumps(math.inf))
inf
>>> ujson.loads(ujson.dumps(math.inf))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Expected object or value
```
... but this isn't necessarily a problem here, we are not seeing proper strings after all. I stopped searching where the quotation marks are lost for today, but maybe some of you can use this information when tracking down the root of this bug :)

---

Since I need the graphs tomorrow, this is my temporary solution, maybe it will help others that reach this topic:
```patch
diff --git a/optuna_dashboard/_serializer.py b/optuna_dashboard/_serializer.py
index 1252ce4..7c7fdd4 100644
--- a/optuna_dashboard/_serializer.py
+++ b/optuna_dashboard/_serializer.py
@@ -1,4 +1,5 @@
 import json
+import math
 from typing import Any
 from typing import Dict
 from typing import List
@@ -99,7 +100,9 @@ def serialize_study_detail(
         )
 
     serialized["trials"] = [
-        serialize_frozen_trial(summary._study_id, trial) for trial in trials
+        serialize_frozen_trial(summary._study_id, trial)
+        for trial in trials
+        if trial.values is None or math.inf not in trial.values
     ]
 
     serialized["intersection_search_space"] = serialize_search_space(intersection)
```

I wouldn't consider this a full solution for the issue though. As a user, I would be surprised if these trials would just vanish without warning, so I would at least make this behavior opt-in.

**Comment by WilliamCappelletti** [comment]
Any updates on this?

**Comment by c-bata** [comment]
Hi, thank you for using optuna-dashboard and submitting an issue. I will work on this.

**Comment by MRV1N2** [comment]
I think the same is happend if a study returns nan.
