### ISSUE TITLE
dashboard inside of the jupyterlab

### ISSUE THREAD

**Issue by z7ye** [optuna/optuna-dashboard#33]
This is more like a question rather than feature request.

I am running a jupyterlab inside of docker container. just wonder if it's possible to use the dashboard inside of the jupyterlab. is there is anything jupyterlab extension that support it? Thanks a lot in advance.

**Comment by NogaGershonB** [comment]
Hi @z7ye,
did you mange to open it at all through jupyer lab?
I try to open it but it just says it's loading and nothing happens. 

Thanks,
Noga

**Comment by c-bata** [comment]
Hi! I have read the following documentation to implement the JupyterLab Extension.
https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#other-resources

* Provide an interface for Tornado framework: We need to implement adapter between WSGI interface (Bottle) and Tornado since optuna-dashboard is built on Bottle framework and JupyterLab extension should be written with Tornado framework.
* Use an API client provided by JupyterLab JS extension: optuna-dashboard uses Axios, but we also need to implement with an API client of JupyterLab. It makes more difficult to 

These changes require a lot of effort and maintenance costs are not small. So let me close this issue.
