### ISSUE TITLE
Option to hide Http logging 

### ISSUE THREAD

**Issue by Guillaume227** [optuna/optuna-dashboard#590]
# Feature Request

After launching the dashboard, my terminal quickly fills up with http-related log lines, which makes me lose track of interesting output I had above:
```
127.0.0.1 - - [30/Aug/2023 02:45:06] "GET /dashboard/studies/0 HTTP/1.1" 200 4145
127.0.0.1 - - [30/Aug/2023 02:45:08] "GET /static/bundle.js HTTP/1.1" 200 2200065
127.0.0.1 - - [30/Aug/2023 02:45:09] "GET /api/meta HTTP/1.1" 200 32
...
```
I would think that output is not relevant to the great majority of end users and my suggestion would be to hide it by default.
If not hidden by default, an option to hide it would be very welcome.

**Comment by c-bata** [comment]
Thank you for the suggestion.
Since the control of server logs is the responsibility of the WSGI server, if you wish to customize the logs, I recommend you to use Gunicorn or uWSGI.
[https://optuna-dashboard.readthedocs.io/en/latest/getting-started.html#using-gunicorn-or-uwsgi-server]

So I don't plan to add extensive customizability to the optuna-dashboard command, but I'm open to accepting a PR that adds a `--silent` or `-q` option.

**Comment by c-bata** [comment]
I've just checked the options for the wsgiref server that optuna-dashboard uses by default, and I couldn't find an option to disable server logs. So let me close this issue.
https://docs.python.org/3/library/wsgiref.html

Again, if you wish to disable server logs, please consider using Gunicorn or uWSGI.
