### ISSUE TITLE
Running trials not showing in the Timeline graph

### ISSUE THREAD

**Issue by mikazlopes** [optuna/optuna-dashboard#820]
### Description

In the Timeline graph, the Trials status that completed, were pruned or failed, displays correctly with the correct duration in terms of bar length. The running trials are not displayed, it is just an empty space, they eventually show when they complete, fail or are pruned.

<img width="701" alt="image" src="https://github.com/optuna/optuna-dashboard/assets/25713129/c2b8c651-09fd-4ebc-bd95-326139516319">

### How to Reproduce

Start the Trials and check the Timeline horizontal bar graph in the dashboard. Trials only start showing if they fail, are completed or are pruned.

### Python version

3.10

### Optuna version

3.5.0

### optuna-dashboard version or git revision

0.14.0

### Web browser

Same behavior on all browsers

**Comment by nabenabe0928** [comment]
Thank you for the report, and fortunately, this issue was already solved in this PR:
- https://github.com/optuna/optuna-dashboard/pull/731
Hence, the timeline plot should be visualized as intended after the new version is released.
For now, please use the HEAD of the main branch by the following command:
```shell
$ pip install git+https://github.com/optuna/optuna-integration@main
```

**Comment by mikazlopes** [comment]
Thank you for the quick reply

**Comment by mikazlopes** [comment]
Quick question the pip install, is it for optuna-integration or optuna-dashboard? It should be optuna-dashboard right?

**Comment by nabenabe0928** [comment]
@mikazlopes 
Sorry, it was `optuna-dashboard` not `optuna-integration`.

>The dashboard stays stuck saying loading and I had this line on my console

Hm, it works in my environment...
```shell
$ python -c "import optuna_dashboard; print(optuna_dashboard.__version__)"
optuna>=3.6.0 is required for PedAnovaImportanceEvaluator.
0.14.0

$ optuna-dashboard sqlite:///dev-test.db
optuna>=3.6.0 is required for PedAnovaImportanceEvaluator.
[2024-03-05 04:00:00 +0100] [13234] [INFO] Starting gunicorn 20.0.4
[2024-03-05 04:00:00 +0100] [13234] [INFO] Listening at: http://127.0.0.1:8080 (13234)
[2024-03-05 04:00:00 +0100] [13234] [INFO] Using worker: threads
[2024-03-05 04:00:00 +0100] [13256] [INFO] Booting worker with pid: 13256

$ python -c "import optuna; print(optuna.__version__)"
3.5.0
```

Did you make sure that your local host 8080 was not in use when you tried launching the dashboard?

**Comment by c-bata** [comment]
@mikazlopes @nabenabe0928  Thank you for trying out the Optuna Dashboard!

Actually, the command `pip install git+https://github.com/optuna/optuna-dashboard@main` doesn't work as it stands because Optuna Dashboard requires a pre-built JavaScript file. You'll have to wait for the next minor release, or alternatively, you can use the development version in the following steps:

```
$ git clone git@github.com:optuna/optuna-dashboard.git
$ cd optuna-dashboard/
$ npm install
$ npm run build:dev
$ pip install .
```

Please check out [CONTRIBUTING.md](https://github.com/optuna/optuna-dashboard/blob/main/CONTRIBUTING.md) for further details.

**Comment by nabenabe0928** [comment]
@c-bata 
Thank you for your comment and sorry for the confusion, @mikazlopes ..!
