### ISSUE TITLE
Plotly state is lost every x seconds (when refreshing)

### ISSUE THREAD

**Issue by simonhessner** [optuna/optuna-dashboard#91]
# Bug reports

When refreshing is enabled and you select some option in a plotly graph, e.g. "Show closest data on hover", this setting is lost whenever the dashboard refreshes.

## Expected Behavior

The setting should be kept in the same way that settings like "log scale" or the selected parameters are kept.

## Current Behavior and Steps to Reproduce

As described above.

I can try to investigate this bug and implement a solution if nobody is currently working on it already.

## Context
Newest verion of optuna and optuna-dashboard.

**Comment by c-bata** [comment]
This issue is duplicated with https://github.com/optuna/optuna-dashboard/issues/17. When updating data to plot, the state will be reset. This is the reason why I added a select box to disable the API polling. See #18 for more details.

> The setting should be kept in the same way that settings like "log scale" or the selected parameters are kept.

As far as I know, it is impossible. If you are familiar with Plotly.js and there are something solution, it is very welcome to open a pull request.

**Comment by simonhessner** [comment]
Thank you. I think there should be some way to do it and I'll try tonight.
